### ISSUE TITLE
TASK: [arvados-api | Run application configuration script] psql failure

### ISSUE THREAD

**Issue by brainstorm** [guillermo-carrasco/arvados-ansible#23]
Got the following error while running this workbench task:

```
psql:/var/www/arvados-api/current/db/structure.sql:15: ERROR:  syntax error at or near "EXTENSION"
LINE 1: CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalo...
               ^
rake aborted!
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near ","
LINE 1: NOTIFY logs, '1'
                   ^
: NOTIFY logs, '1'
```

`vagrant ssh workbench` and running the offending command again seems to solve the issue for now:

```
/bin/bash /usr/local/bin/arvados-api-server-upgrade.sh"
```

**Comment by brainstorm** [comment]
@guillermo-carrasco I know you mentioned it on trello, putting it here to discuss with Curoverse team...

**Comment by brettcs** [comment]
What version of PostgreSQL is this server running?

Also, I note that in the description you refer to setting up Workbench, but the script and its error are referring to the API server.  Are you setting them both up on the same host?

**Comment by brettcs** [comment]
If you install postgresql-contrib package before running the command, does that resolve the issue?  We don't necessarily require that (see the discussion [in our bug tracker](https://dev.arvados.org/issues/7987)), but it would be useful to know whether this is identical to a related issue we've seen in the past.

**Comment by brainstorm** [comment]
Hello @brettcs, thanks for your feedback! Yes, the workbench host is holding a bunch of roles at the moment:

```
- hosts: workbench
  sudo_user: "root"
  sudo: yes
  vars_files:
      - roles/arvados-sso/vars/main.yaml
  roles:
      - { role: rvm_io.rvm1-ruby, tags: ruby, sudo: True }
      - postgres
      - passenger
      - arvados-api
      - arvados-git
      - arvados-workbench
```

The PostgreSQL version is slightly old since we are currently targeting baremetal Centos 6.6 (traditional legacy-ish academic clusters that don't support docker that well yet):

```
#postgres --version
postgres (PostgreSQL) 8.4.20
```

I've just added the `postgres-contrib` package as you suggested on https://github.com/brainstorm/arvados-ansible/commit/4dc8bf870570cbc63f5d4f78dceb5f806652c3db, and reran the deployment of the `workbench` machine, I'll let you know how it goes.
